# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tidm.proto\x12\x03idm\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"g\n\x17TokenValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"3\n\x0fGenericResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb1\x01\n\nIDMService\x12.\n\x05Login\x12\x11.idm.LoginRequest\x1a\x12.idm.LoginResponse\x12@\n\rValidateToken\x12\x11.idm.TokenRequest\x1a\x1c.idm.TokenValidationResponse\x12\x31\n\x06Logout\x12\x11.idm.TokenRequest\x1a\x14.idm.GenericResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=18
  _globals['_LOGINREQUEST']._serialized_end=65
  _globals['_LOGINRESPONSE']._serialized_start=67
  _globals['_LOGINRESPONSE']._serialized_end=97
  _globals['_TOKENREQUEST']._serialized_start=99
  _globals['_TOKENREQUEST']._serialized_end=128
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=130
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=233
  _globals['_GENERICRESPONSE']._serialized_start=235
  _globals['_GENERICRESPONSE']._serialized_end=286
  _globals['_IDMSERVICE']._serialized_start=289
  _globals['_IDMSERVICE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
